/* Generated by Yosys 0.55+146 (git sha1 262b00d5e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "./for_no_trojan_RTL/trojan0-7.v:1.1-20.10" *)
module Trojan_module(clk, rst, \key[0] , \key[1] , \key[2] , \key[3] , \key[4] , \key[5] , \key[6] , \key[7] , \key[8] , \key[9] , \key[10] , \key[11] , \key[12] , \key[13] , \key[14] , \key[15] , \key[16] , \key[17] , \key[18] 
, \key[19] , \key[20] , \key[21] , \key[22] , \key[23] , \key[24] , \key[25] , \key[26] , \key[27] , \key[28] , \key[29] , \key[30] , \key[31] , \key[32] , \key[33] , \key[34] , \key[35] , \key[36] , \key[37] , \key[38] , \key[39] 
, \key[40] , \key[41] , \key[42] , \key[43] , \key[44] , \key[45] , \key[46] , \key[47] , \key[48] , \key[49] , \key[50] , \key[51] , \key[52] , \key[53] , \key[54] , \key[55] , \key[56] , \key[57] , \key[58] , \key[59] , \key[60] 
, \key[61] , \key[62] , \key[63] , \key[64] , \key[65] , \key[66] , \key[67] , \key[68] , \key[69] , \key[70] , \key[71] , \key[72] , \key[73] , \key[74] , \key[75] , \key[76] , \key[77] , \key[78] , \key[79] , \key[80] , \key[81] 
, \key[82] , \key[83] , \key[84] , \key[85] , \key[86] , \key[87] , \key[88] , \key[89] , \key[90] , \key[91] , \key[92] , \key[93] , \key[94] , \key[95] , \key[96] , \key[97] , \key[98] , \key[99] , \key[100] , \key[101] , \key[102] 
, \key[103] , \key[104] , \key[105] , \key[106] , \key[107] , \key[108] , \key[109] , \key[110] , \key[111] , \key[112] , \key[113] , \key[114] , \key[115] , \key[116] , \key[117] , \key[118] , \key[119] , \key[120] , \key[121] , \key[122] , \key[123] 
, \key[124] , \key[125] , \key[126] , \key[127] , \load[0] , \load[1] , \load[2] , \load[3] , \load[4] , \load[5] , \load[6] , \load[7] , \load[8] , \load[9] , \load[10] , \load[11] , \load[12] , \load[13] , \load[14] , \load[15] , \load[16] 
, \load[17] , \load[18] , \load[19] , \load[20] , \load[21] , \load[22] , \load[23] , \load[24] , \load[25] , \load[26] , \load[27] , \load[28] , \load[29] , \load[30] , \load[31] , \load[32] , \load[33] , \load[34] , \load[35] , \load[36] , \load[37] 
, \load[38] , \load[39] , \load[40] , \load[41] , \load[42] , \load[43] , \load[44] , \load[45] , \load[46] , \load[47] , \load[48] , \load[49] , \load[50] , \load[51] , \load[52] , \load[53] , \load[54] , \load[55] , \load[56] , \load[57] , \load[58] 
, \load[59] , \load[60] , \load[61] , \load[62] , \load[63] );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _000_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _001_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _002_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _003_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _004_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _005_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _006_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _007_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _008_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _009_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _010_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _011_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _012_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _013_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _014_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _015_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _016_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _017_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _018_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _019_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _020_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _021_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _022_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _023_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _024_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _025_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _026_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _027_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _028_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _029_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _030_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _031_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _032_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _033_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _034_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _035_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _036_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _037_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _038_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _039_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _040_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _041_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _042_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _043_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _044_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _045_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _046_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _047_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _048_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _049_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _050_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _051_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _052_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _053_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _054_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _055_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _056_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _057_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _058_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _059_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _060_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _061_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[0] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[10] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[11] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[12] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[13] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[14] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[15] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[16] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[17] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[18] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[19] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[1] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[2] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[3] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[4] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[5] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[6] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[7] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[8] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:7.17-7.24" *)
  wire \counter[9] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[0] ;
  wire \key[0] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[100] ;
  wire \key[100] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[101] ;
  wire \key[101] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[102] ;
  wire \key[102] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[103] ;
  wire \key[103] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[104] ;
  wire \key[104] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[105] ;
  wire \key[105] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[106] ;
  wire \key[106] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[107] ;
  wire \key[107] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[108] ;
  wire \key[108] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[109] ;
  wire \key[109] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[10] ;
  wire \key[10] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[110] ;
  wire \key[110] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[111] ;
  wire \key[111] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[112] ;
  wire \key[112] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[113] ;
  wire \key[113] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[114] ;
  wire \key[114] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[115] ;
  wire \key[115] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[116] ;
  wire \key[116] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[117] ;
  wire \key[117] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[118] ;
  wire \key[118] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[119] ;
  wire \key[119] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[11] ;
  wire \key[11] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[120] ;
  wire \key[120] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[121] ;
  wire \key[121] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[122] ;
  wire \key[122] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[123] ;
  wire \key[123] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[124] ;
  wire \key[124] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[125] ;
  wire \key[125] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[126] ;
  wire \key[126] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[127] ;
  wire \key[127] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[12] ;
  wire \key[12] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[13] ;
  wire \key[13] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[14] ;
  wire \key[14] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[15] ;
  wire \key[15] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[16] ;
  wire \key[16] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[17] ;
  wire \key[17] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[18] ;
  wire \key[18] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[19] ;
  wire \key[19] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[1] ;
  wire \key[1] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[20] ;
  wire \key[20] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[21] ;
  wire \key[21] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[22] ;
  wire \key[22] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[23] ;
  wire \key[23] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[24] ;
  wire \key[24] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[25] ;
  wire \key[25] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[26] ;
  wire \key[26] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[27] ;
  wire \key[27] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[28] ;
  wire \key[28] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[29] ;
  wire \key[29] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[2] ;
  wire \key[2] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[30] ;
  wire \key[30] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[31] ;
  wire \key[31] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[32] ;
  wire \key[32] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[33] ;
  wire \key[33] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[34] ;
  wire \key[34] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[35] ;
  wire \key[35] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[36] ;
  wire \key[36] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[37] ;
  wire \key[37] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[38] ;
  wire \key[38] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[39] ;
  wire \key[39] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[3] ;
  wire \key[3] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[40] ;
  wire \key[40] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[41] ;
  wire \key[41] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[42] ;
  wire \key[42] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[43] ;
  wire \key[43] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[44] ;
  wire \key[44] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[45] ;
  wire \key[45] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[46] ;
  wire \key[46] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[47] ;
  wire \key[47] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[48] ;
  wire \key[48] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[49] ;
  wire \key[49] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[4] ;
  wire \key[4] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[50] ;
  wire \key[50] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[51] ;
  wire \key[51] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[52] ;
  wire \key[52] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[53] ;
  wire \key[53] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[54] ;
  wire \key[54] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[55] ;
  wire \key[55] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[56] ;
  wire \key[56] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[57] ;
  wire \key[57] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[58] ;
  wire \key[58] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[59] ;
  wire \key[59] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[5] ;
  wire \key[5] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[60] ;
  wire \key[60] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[61] ;
  wire \key[61] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[62] ;
  wire \key[62] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[63] ;
  wire \key[63] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[64] ;
  wire \key[64] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[65] ;
  wire \key[65] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[66] ;
  wire \key[66] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[67] ;
  wire \key[67] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[68] ;
  wire \key[68] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[69] ;
  wire \key[69] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[6] ;
  wire \key[6] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[70] ;
  wire \key[70] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[71] ;
  wire \key[71] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[72] ;
  wire \key[72] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[73] ;
  wire \key[73] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[74] ;
  wire \key[74] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[75] ;
  wire \key[75] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[76] ;
  wire \key[76] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[77] ;
  wire \key[77] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[78] ;
  wire \key[78] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[79] ;
  wire \key[79] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[7] ;
  wire \key[7] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[80] ;
  wire \key[80] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[81] ;
  wire \key[81] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[82] ;
  wire \key[82] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[83] ;
  wire \key[83] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[84] ;
  wire \key[84] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[85] ;
  wire \key[85] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[86] ;
  wire \key[86] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[87] ;
  wire \key[87] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[88] ;
  wire \key[88] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[89] ;
  wire \key[89] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[8] ;
  wire \key[8] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[90] ;
  wire \key[90] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[91] ;
  wire \key[91] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[92] ;
  wire \key[92] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[93] ;
  wire \key[93] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[94] ;
  wire \key[94] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[95] ;
  wire \key[95] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[96] ;
  wire \key[96] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[97] ;
  wire \key[97] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[98] ;
  wire \key[98] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[99] ;
  wire \key[99] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:4.24-4.27" *)
  input \key[9] ;
  wire \key[9] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[0] ;
  wire \load[0] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[10] ;
  wire \load[10] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[11] ;
  wire \load[11] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[12] ;
  wire \load[12] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[13] ;
  wire \load[13] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[14] ;
  wire \load[14] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[15] ;
  wire \load[15] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[16] ;
  wire \load[16] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[17] ;
  wire \load[17] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[18] ;
  wire \load[18] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[19] ;
  wire \load[19] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[1] ;
  wire \load[1] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[20] ;
  wire \load[20] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[21] ;
  wire \load[21] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[22] ;
  wire \load[22] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[23] ;
  wire \load[23] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[24] ;
  wire \load[24] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[25] ;
  wire \load[25] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[26] ;
  wire \load[26] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[27] ;
  wire \load[27] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[28] ;
  wire \load[28] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[29] ;
  wire \load[29] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[2] ;
  wire \load[2] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[30] ;
  wire \load[30] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[31] ;
  wire \load[31] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[32] ;
  wire \load[32] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[33] ;
  wire \load[33] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[34] ;
  wire \load[34] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[35] ;
  wire \load[35] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[36] ;
  wire \load[36] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[37] ;
  wire \load[37] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[38] ;
  wire \load[38] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[39] ;
  wire \load[39] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[3] ;
  wire \load[3] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[40] ;
  wire \load[40] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[41] ;
  wire \load[41] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[42] ;
  wire \load[42] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[43] ;
  wire \load[43] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[44] ;
  wire \load[44] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[45] ;
  wire \load[45] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[46] ;
  wire \load[46] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[47] ;
  wire \load[47] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[48] ;
  wire \load[48] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[49] ;
  wire \load[49] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[4] ;
  wire \load[4] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[50] ;
  wire \load[50] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[51] ;
  wire \load[51] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[52] ;
  wire \load[52] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[53] ;
  wire \load[53] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[54] ;
  wire \load[54] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[55] ;
  wire \load[55] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[56] ;
  wire \load[56] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[57] ;
  wire \load[57] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[58] ;
  wire \load[58] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[59] ;
  wire \load[59] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[5] ;
  wire \load[5] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[60] ;
  wire \load[60] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[61] ;
  wire \load[61] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[62] ;
  wire \load[62] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[63] ;
  wire \load[63] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[6] ;
  wire \load[6] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[7] ;
  wire \load[7] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[8] ;
  wire \load[8] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:5.23-5.27" *)
  output \load[9] ;
  wire \load[9] ;
  (* src = "./for_no_trojan_RTL/trojan0-7.v:3.16-3.19" *)
  input rst;
  wire rst;
  INV _097_ (
    .A(\counter[16] ),
    .Y(_083_)
  );
  INV _098_ (
    .A(\counter[10] ),
    .Y(_084_)
  );
  INV _099_ (
    .A(\counter[4] ),
    .Y(_085_)
  );
  INV _100_ (
    .A(\counter[3] ),
    .Y(_086_)
  );
  INV _101_ (
    .A(\counter[5] ),
    .Y(_087_)
  );
  INV _102_ (
    .A(\counter[9] ),
    .Y(_088_)
  );
  INV _103_ (
    .A(\counter[11] ),
    .Y(_089_)
  );
  INV _104_ (
    .A(\counter[15] ),
    .Y(_090_)
  );
  INV _105_ (
    .A(\counter[17] ),
    .Y(_091_)
  );
  XOR2 _106_ (
    .A(\key[112] ),
    .B(\counter[16] ),
    .Y(_050_)
  );
  XOR2 _107_ (
    .A(\key[72] ),
    .B(\counter[8] ),
    .Y(_049_)
  );
  XOR2 _108_ (
    .A(\key[108] ),
    .B(\counter[14] ),
    .Y(_048_)
  );
  XOR2 _109_ (
    .A(\key[74] ),
    .B(\counter[10] ),
    .Y(_047_)
  );
  XOR2 _110_ (
    .A(\key[104] ),
    .B(\counter[12] ),
    .Y(_046_)
  );
  XOR2 _111_ (
    .A(\counter[12] ),
    .B(\key[76] ),
    .Y(_045_)
  );
  XOR2 _112_ (
    .A(\counter[10] ),
    .B(\key[100] ),
    .Y(_044_)
  );
  XOR2 _113_ (
    .A(\counter[14] ),
    .B(\key[78] ),
    .Y(_042_)
  );
  XOR2 _114_ (
    .A(\counter[8] ),
    .B(\key[96] ),
    .Y(_041_)
  );
  XOR2 _115_ (
    .A(\counter[16] ),
    .B(\key[80] ),
    .Y(_040_)
  );
  XOR2 _116_ (
    .A(\counter[6] ),
    .B(\key[92] ),
    .Y(_039_)
  );
  XOR2 _117_ (
    .A(\key[82] ),
    .B(\counter[18] ),
    .Y(_038_)
  );
  XOR2 _118_ (
    .A(\key[88] ),
    .B(\counter[4] ),
    .Y(_032_)
  );
  XOR2 _119_ (
    .A(\key[84] ),
    .B(\counter[0] ),
    .Y(_037_)
  );
  XOR2 _120_ (
    .A(\key[84] ),
    .B(\counter[2] ),
    .Y(_036_)
  );
  XOR2 _121_ (
    .A(\counter[2] ),
    .B(\key[86] ),
    .Y(_035_)
  );
  XOR2 _122_ (
    .A(\key[80] ),
    .B(\counter[0] ),
    .Y(_034_)
  );
  XOR2 _123_ (
    .A(\key[76] ),
    .B(\counter[18] ),
    .Y(_031_)
  );
  XOR2 _124_ (
    .A(\counter[6] ),
    .B(\key[90] ),
    .Y(_030_)
  );
  XOR2 _125_ (
    .A(\counter[16] ),
    .B(\key[72] ),
    .Y(_029_)
  );
  XOR2 _126_ (
    .A(\counter[8] ),
    .B(\key[92] ),
    .Y(_028_)
  );
  XOR2 _127_ (
    .A(\counter[14] ),
    .B(\key[68] ),
    .Y(_027_)
  );
  XOR2 _128_ (
    .A(\counter[10] ),
    .B(\key[94] ),
    .Y(_026_)
  );
  XOR2 _129_ (
    .A(\counter[12] ),
    .B(\key[64] ),
    .Y(_025_)
  );
  XOR2 _130_ (
    .A(\counter[12] ),
    .B(\key[96] ),
    .Y(_024_)
  );
  XOR2 _131_ (
    .A(\counter[10] ),
    .B(\key[60] ),
    .Y(_023_)
  );
  XOR2 _132_ (
    .A(\counter[14] ),
    .B(\key[98] ),
    .Y(_021_)
  );
  XOR2 _133_ (
    .A(\counter[8] ),
    .B(\key[56] ),
    .Y(_020_)
  );
  XOR2 _134_ (
    .A(\counter[16] ),
    .B(\key[100] ),
    .Y(_019_)
  );
  XOR2 _135_ (
    .A(\counter[6] ),
    .B(\key[52] ),
    .Y(_018_)
  );
  XOR2 _136_ (
    .A(\counter[18] ),
    .B(\key[102] ),
    .Y(_017_)
  );
  XOR2 _137_ (
    .A(\counter[4] ),
    .B(\key[48] ),
    .Y(_016_)
  );
  XOR2 _138_ (
    .A(\key[104] ),
    .B(\counter[0] ),
    .Y(_015_)
  );
  XOR2 _139_ (
    .A(\counter[2] ),
    .B(\key[44] ),
    .Y(_014_)
  );
  XOR2 _140_ (
    .A(\counter[2] ),
    .B(\key[106] ),
    .Y(_013_)
  );
  XOR2 _141_ (
    .A(\counter[0] ),
    .B(\key[40] ),
    .Y(_012_)
  );
  XOR2 _142_ (
    .A(\key[108] ),
    .B(\counter[4] ),
    .Y(_010_)
  );
  XOR2 _143_ (
    .A(\counter[18] ),
    .B(\key[36] ),
    .Y(_009_)
  );
  XOR2 _144_ (
    .A(\counter[6] ),
    .B(\key[110] ),
    .Y(_008_)
  );
  XOR2 _145_ (
    .A(\counter[16] ),
    .B(\key[32] ),
    .Y(_007_)
  );
  XOR2 _146_ (
    .A(\key[112] ),
    .B(\counter[8] ),
    .Y(_006_)
  );
  XOR2 _147_ (
    .A(\counter[14] ),
    .B(\key[28] ),
    .Y(_005_)
  );
  XOR2 _148_ (
    .A(\counter[10] ),
    .B(\key[114] ),
    .Y(_004_)
  );
  XOR2 _149_ (
    .A(\counter[12] ),
    .B(\key[24] ),
    .Y(_003_)
  );
  XOR2 _150_ (
    .A(\counter[12] ),
    .B(\key[116] ),
    .Y(_002_)
  );
  XOR2 _151_ (
    .A(\counter[10] ),
    .B(\key[20] ),
    .Y(_001_)
  );
  XOR2 _152_ (
    .A(\counter[14] ),
    .B(\key[118] ),
    .Y(_062_)
  );
  XOR2 _153_ (
    .A(\counter[8] ),
    .B(\key[16] ),
    .Y(_061_)
  );
  XOR2 _154_ (
    .A(\counter[16] ),
    .B(\key[120] ),
    .Y(_060_)
  );
  XOR2 _155_ (
    .A(\counter[6] ),
    .B(\key[12] ),
    .Y(_059_)
  );
  XOR2 _156_ (
    .A(\counter[18] ),
    .B(\key[122] ),
    .Y(_054_)
  );
  XOR2 _157_ (
    .A(\counter[4] ),
    .B(\key[8] ),
    .Y(_043_)
  );
  XOR2 _158_ (
    .A(\counter[0] ),
    .B(\key[124] ),
    .Y(_033_)
  );
  XOR2 _159_ (
    .A(\counter[2] ),
    .B(\key[4] ),
    .Y(_022_)
  );
  XOR2 _160_ (
    .A(\counter[2] ),
    .B(\key[126] ),
    .Y(_011_)
  );
  XOR2 _161_ (
    .A(\counter[0] ),
    .B(\key[0] ),
    .Y(_000_)
  );
  OR2 _162_ (
    .A(\counter[1] ),
    .B(rst),
    .Y(_063_)
  );
  OR2 _163_ (
    .A(\counter[2] ),
    .B(rst),
    .Y(_064_)
  );
  NOR2 _164_ (
    .A(rst),
    .B(_086_),
    .Y(_065_)
  );
  NOR2 _165_ (
    .A(_085_),
    .B(rst),
    .Y(_066_)
  );
  NOR2 _166_ (
    .A(rst),
    .B(_087_),
    .Y(_067_)
  );
  OR2 _167_ (
    .A(\counter[6] ),
    .B(rst),
    .Y(_068_)
  );
  OR2 _168_ (
    .A(rst),
    .B(\counter[7] ),
    .Y(_069_)
  );
  OR2 _169_ (
    .A(\counter[8] ),
    .B(rst),
    .Y(_070_)
  );
  NOR2 _170_ (
    .A(rst),
    .B(_088_),
    .Y(_071_)
  );
  NOR2 _171_ (
    .A(_084_),
    .B(rst),
    .Y(_072_)
  );
  NOR2 _172_ (
    .A(rst),
    .B(_089_),
    .Y(_073_)
  );
  OR2 _173_ (
    .A(\counter[12] ),
    .B(rst),
    .Y(_074_)
  );
  OR2 _174_ (
    .A(rst),
    .B(\counter[13] ),
    .Y(_075_)
  );
  OR2 _175_ (
    .A(\counter[14] ),
    .B(rst),
    .Y(_076_)
  );
  NOR2 _176_ (
    .A(rst),
    .B(_090_),
    .Y(_077_)
  );
  NOR2 _177_ (
    .A(_083_),
    .B(rst),
    .Y(_078_)
  );
  NOR2 _178_ (
    .A(rst),
    .B(_091_),
    .Y(_079_)
  );
  OR2 _179_ (
    .A(\counter[18] ),
    .B(rst),
    .Y(_080_)
  );
  OR2 _180_ (
    .A(rst),
    .B(\counter[19] ),
    .Y(_081_)
  );
  XNOR2 _181_ (
    .A(\counter[13] ),
    .B(\counter[19] ),
    .Y(_092_)
  );
  XOR2 _182_ (
    .A(\counter[16] ),
    .B(\counter[4] ),
    .Y(_093_)
  );
  NAND2 _183_ (
    .A(_092_),
    .B(_093_),
    .Y(_094_)
  );
  NOR2 _184_ (
    .A(_092_),
    .B(_093_),
    .Y(_095_)
  );
  NOR2 _185_ (
    .A(rst),
    .B(_095_),
    .Y(_096_)
  );
  NAND2 _186_ (
    .A(_094_),
    .B(_096_),
    .Y(_082_)
  );
  XOR2 _187_ (
    .A(\counter[0] ),
    .B(\key[64] ),
    .Y(_058_)
  );
  XOR2 _188_ (
    .A(\counter[2] ),
    .B(\key[124] ),
    .Y(_057_)
  );
  XOR2 _189_ (
    .A(\counter[2] ),
    .B(\key[66] ),
    .Y(_056_)
  );
  XOR2 _190_ (
    .A(\counter[0] ),
    .B(\key[120] ),
    .Y(_055_)
  );
  XOR2 _191_ (
    .A(\counter[4] ),
    .B(\key[68] ),
    .Y(_053_)
  );
  XOR2 _192_ (
    .A(\counter[18] ),
    .B(\key[116] ),
    .Y(_052_)
  );
  XOR2 _193_ (
    .A(\key[70] ),
    .B(\counter[6] ),
    .Y(_051_)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _194_ (
    .CK(clk),
    .D(_063_),
    .Q(\counter[0] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _195_ (
    .CK(clk),
    .D(_064_),
    .Q(\counter[1] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _196_ (
    .CK(clk),
    .D(_065_),
    .Q(\counter[2] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _197_ (
    .CK(clk),
    .D(_066_),
    .Q(\counter[3] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _198_ (
    .CK(clk),
    .D(_067_),
    .Q(\counter[4] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _199_ (
    .CK(clk),
    .D(_068_),
    .Q(\counter[5] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _200_ (
    .CK(clk),
    .D(_069_),
    .Q(\counter[6] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _201_ (
    .CK(clk),
    .D(_070_),
    .Q(\counter[7] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _202_ (
    .CK(clk),
    .D(_071_),
    .Q(\counter[8] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _203_ (
    .CK(clk),
    .D(_072_),
    .Q(\counter[9] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _204_ (
    .CK(clk),
    .D(_073_),
    .Q(\counter[10] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _205_ (
    .CK(clk),
    .D(_074_),
    .Q(\counter[11] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _206_ (
    .CK(clk),
    .D(_075_),
    .Q(\counter[12] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _207_ (
    .CK(clk),
    .D(_076_),
    .Q(\counter[13] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _208_ (
    .CK(clk),
    .D(_077_),
    .Q(\counter[14] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _209_ (
    .CK(clk),
    .D(_078_),
    .Q(\counter[15] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _210_ (
    .CK(clk),
    .D(_079_),
    .Q(\counter[16] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _211_ (
    .CK(clk),
    .D(_080_),
    .Q(\counter[17] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _212_ (
    .CK(clk),
    .D(_081_),
    .Q(\counter[18] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:33.5-37.52" *)
  DFFSR _213_ (
    .CK(clk),
    .D(_082_),
    .Q(\counter[19] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _214_ (
    .CK(clk),
    .D(_000_),
    .Q(\load[0] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _215_ (
    .CK(clk),
    .D(_011_),
    .Q(\load[1] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _216_ (
    .CK(clk),
    .D(_022_),
    .Q(\load[2] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _217_ (
    .CK(clk),
    .D(_033_),
    .Q(\load[3] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _218_ (
    .CK(clk),
    .D(_043_),
    .Q(\load[4] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _219_ (
    .CK(clk),
    .D(_054_),
    .Q(\load[5] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _220_ (
    .CK(clk),
    .D(_059_),
    .Q(\load[6] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _221_ (
    .CK(clk),
    .D(_060_),
    .Q(\load[7] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _222_ (
    .CK(clk),
    .D(_061_),
    .Q(\load[8] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _223_ (
    .CK(clk),
    .D(_062_),
    .Q(\load[9] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _224_ (
    .CK(clk),
    .D(_001_),
    .Q(\load[10] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _225_ (
    .CK(clk),
    .D(_002_),
    .Q(\load[11] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _226_ (
    .CK(clk),
    .D(_003_),
    .Q(\load[12] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _227_ (
    .CK(clk),
    .D(_004_),
    .Q(\load[13] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _228_ (
    .CK(clk),
    .D(_005_),
    .Q(\load[14] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _229_ (
    .CK(clk),
    .D(_006_),
    .Q(\load[15] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _230_ (
    .CK(clk),
    .D(_007_),
    .Q(\load[16] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _231_ (
    .CK(clk),
    .D(_008_),
    .Q(\load[17] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _232_ (
    .CK(clk),
    .D(_009_),
    .Q(\load[18] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _233_ (
    .CK(clk),
    .D(_010_),
    .Q(\load[19] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _234_ (
    .CK(clk),
    .D(_012_),
    .Q(\load[20] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _235_ (
    .CK(clk),
    .D(_013_),
    .Q(\load[21] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _236_ (
    .CK(clk),
    .D(_014_),
    .Q(\load[22] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _237_ (
    .CK(clk),
    .D(_015_),
    .Q(\load[23] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _238_ (
    .CK(clk),
    .D(_016_),
    .Q(\load[24] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _239_ (
    .CK(clk),
    .D(_017_),
    .Q(\load[25] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _240_ (
    .CK(clk),
    .D(_018_),
    .Q(\load[26] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _241_ (
    .CK(clk),
    .D(_019_),
    .Q(\load[27] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _242_ (
    .CK(clk),
    .D(_020_),
    .Q(\load[28] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _243_ (
    .CK(clk),
    .D(_021_),
    .Q(\load[29] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _244_ (
    .CK(clk),
    .D(_023_),
    .Q(\load[30] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _245_ (
    .CK(clk),
    .D(_024_),
    .Q(\load[31] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _246_ (
    .CK(clk),
    .D(_025_),
    .Q(\load[32] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _247_ (
    .CK(clk),
    .D(_026_),
    .Q(\load[33] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _248_ (
    .CK(clk),
    .D(_027_),
    .Q(\load[34] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _249_ (
    .CK(clk),
    .D(_028_),
    .Q(\load[35] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _250_ (
    .CK(clk),
    .D(_029_),
    .Q(\load[36] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _251_ (
    .CK(clk),
    .D(_030_),
    .Q(\load[37] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _252_ (
    .CK(clk),
    .D(_031_),
    .Q(\load[38] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _253_ (
    .CK(clk),
    .D(_034_),
    .Q(\load[40] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _254_ (
    .CK(clk),
    .D(_035_),
    .Q(\load[41] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _255_ (
    .CK(clk),
    .D(_036_),
    .Q(\load[42] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _256_ (
    .CK(clk),
    .D(_037_),
    .Q(\load[43] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _257_ (
    .CK(clk),
    .D(_032_),
    .Q(\load[39] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _258_ (
    .CK(clk),
    .D(_038_),
    .Q(\load[45] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _259_ (
    .CK(clk),
    .D(_039_),
    .Q(\load[46] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _260_ (
    .CK(clk),
    .D(_040_),
    .Q(\load[47] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _261_ (
    .CK(clk),
    .D(_041_),
    .Q(\load[48] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _262_ (
    .CK(clk),
    .D(_042_),
    .Q(\load[49] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _263_ (
    .CK(clk),
    .D(_044_),
    .Q(\load[50] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _264_ (
    .CK(clk),
    .D(_045_),
    .Q(\load[51] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _265_ (
    .CK(clk),
    .D(_046_),
    .Q(\load[52] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _266_ (
    .CK(clk),
    .D(_047_),
    .Q(\load[53] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _267_ (
    .CK(clk),
    .D(_048_),
    .Q(\load[54] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _268_ (
    .CK(clk),
    .D(_049_),
    .Q(\load[55] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _269_ (
    .CK(clk),
    .D(_050_),
    .Q(\load[56] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _270_ (
    .CK(clk),
    .D(_051_),
    .Q(\load[57] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _271_ (
    .CK(clk),
    .D(_052_),
    .Q(\load[58] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _272_ (
    .CK(clk),
    .D(_053_),
    .Q(\load[59] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _273_ (
    .CK(clk),
    .D(_055_),
    .Q(\load[60] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _274_ (
    .CK(clk),
    .D(_056_),
    .Q(\load[61] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _275_ (
    .CK(clk),
    .D(_057_),
    .Q(\load[62] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  (* src = "./for_no_trojan_RTL/trojan0-7.v:11.5-18.8" *)
  DFFSR _276_ (
    .CK(clk),
    .D(_058_),
    .Q(\load[63] ),
    .RN(1'h1),
    .SN(1'h1)
  );
  assign \load[44]  = \load[39] ;
endmodule
